### ISSUE TITLE
error with PASS

### ISSUE THREAD

**Issue by JRKrieger37** [warrenlr/PASS#1]
Hi - I am very interested in using this tool to assemble de novo sequences.  I've downloaded the latest version but every time I try to use it I receive the following message.  Any help would be appreciated.
Thanks.

C:\PASS-master\PASS-master\tarballs\pass_v0.3>perl PASS -f "c:\Data\SPARC\BSI\BSI 18061\18061 Search_DENOVO_58\de novo peptides.fasta" -w 1
The getpgrp function is unimplemented at PASS line 151.

**Comment by warrenlr** [comment]
Thank you for your interest in PASS.
This specific error is due to a unix command call to get the process ID.  
I see that you are on a windows system.. a way to have the script by-pass this error is to set -b to your job name.

-b  Basename for your output files (optional)

eg.
C:\PASS-master\PASS-master\tarballs\pass_v0.3>perl PASS -f "c:\Data\SPARC\BSI\BSI 18061\18061 Search_DENOVO_58\de novo peptides.fasta" -w 1 -b MYRUN

that should do the trick.
